app/__init__.py
from flask import Flask
from app.config import load_configurations, configure_logging
from .views import webhook_blueprint
from app.utils.model import *
from app.services.user_types import *
import os
from flask import Flask, render_template, request, jsonify
from werkzeug.security import generate_password_hash
from flask_jwt_extended import JWTManager, jwt_required, create_access_token, get_jwt_identity
from werkzeug.security import check_password_hash
from datetime import timedelta
from sqlalchemy.exc import PendingRollbackError
from flask_cors import CORS

app = Flask(__name__,static_folder='static')
CORS(app)
CORS(app, origins=['http://localhost:8000','https://clava.onrender.com'])
app.config["SQLALCHEMY_DATABASE_URI"] = os.getenv("DATABASE_URL")
app.config['TEMPLATES_AUTO_RELOAD'] = True

app.config['SECRET_KEY'] = '112233445566'
app.config['JWT_EXPIRATION_DELTA'] = timedelta(days=2)

jwt = JWTManager(app)


# Load configurations and logging settings
load_configurations(app)
configure_logging()

app.register_blueprint(webhook_blueprint)

@app.route('/login', methods=['POST', 'GET'])
def login():
    if request.method == 'GET':
        return render_template('login.html')
    else:
        data = request.get_json()
        username = data['username']
        password = data['password']
        if username.startswith('0'):
            username = username.replace('0', '263', 1)

        try:
            user = session.query(User).filter_by(username=username).first()
        except:
            user = None

        if not user:
            return jsonify(message='Wrong Login Credentials!')

        if check_password_hash(user.password, password):
            access_token = create_access_token(identity=user.id, additional_claims={
            'name': user.username,
            'password': user.password
            })
            return jsonify(message='success', access_token=access_token,user_name=user.username), 200
        else:
            return jsonify(message='Wrong Login Credentials.'), 401

@app.route('/register', methods=['POST', 'GET'])
def register():
    if request.method == 'GET':
        return render_template('register.html')
    else:
        data = request.get_json()
        username = data['username']
        password = data['password']
        if username.startswith('0'):
            username = username.replace('0', '263', 1)
        try:
            user = session.query(User).filter_by(username=username).first()
        except:
            user = None

        if user:
            return jsonify(message='User already exists')

        hashed_password = generate_password_hash(password)
        user_subscription = session.query(Subscription).filter_by(mobile_number=username).first()

        if not user_subscription:
            user_subscription = Subscription(mobile_number=username, subscription_status='welcome', user_name=username, user_status='new_user', user_type='new_user', user_activity='active')
            session.add(user_subscription)

        try:
            session.commit()
        except PendingRollbackError:
            return jsonify(message='An error occurred during registration. Please try again.'), 500

        user = User(username=username, password=hashed_password, subscription_id=user_subscription.id)
        session.add(user)

        try:
            session.commit()
        except PendingRollbackError:
            return jsonify(message='An error occurred during registration. Please try again.'), 500

        # Generate the access token
        access_token = create_access_token(identity=user.id, additional_claims={
            'name': user.username,
            'password': user.password
        })

        return jsonify(message='success', access_token=access_token,user_name=user.username), 200

app/views.py
import logging
import json
from flask import Flask, render_template,redirect, url_for
from flask import Blueprint, request, jsonify, current_app
from flask_jwt_extended import jwt_required, get_jwt_identity
from .decorators.security import signature_required
from .utils.whatsapp_utils import (
    process_whatsapp_message,
    is_valid_whatsapp_message,
    send_message_template,
)
from app.utils.model import *
webhook_blueprint = Blueprint("webhook", __name__)

def handle_message():
    body = request.get_json()
    if (
        body.get("entry", [{}])[0]
        .get("changes", [{}])[0]
        .get("value", {})
        .get("statuses")
    ):
        # logging.info("Received a WhatsApp status update.")
        return jsonify({"status": "ok"}), 200

    try:
        if is_valid_whatsapp_message(body):
            process_whatsapp_message(body)
            return jsonify({"status": "ok"}), 200
        
        else:
            send_message_template(body)
            return jsonify({"status": "ok"}), 200
    except json.JSONDecodeError:
        logging.error("Failed to decode JSON")
        return jsonify({"status": "error", "message": "Invalid JSON provided"}), 400
def verify():
    mode = request.args.get("hub.mode")
    token = request.args.get("hub.verify_token")
    challenge = request.args.get("hub.challenge")
    if mode and token:
        if mode == "subscribe" and token == current_app.config["VERIFY_TOKEN"]:
            logging.info("WEBHOOK_VERIFIED")
            return challenge, 200
        else:
            logging.info("VERIFICATION_FAILED")
            return jsonify({"status": "error", "message": "Verification failed"}), 403
    else:
        logging.info("MISSING_PARAMETER")
        return jsonify({"status": "error", "message": "Missing parameters"}), 400

@webhook_blueprint.route("/webhook", methods=["POST","GET"])
# @signature_required
def webhook():
    if request.method == "GET":
        return verify()
    elif request.method == "POST":
        return handle_message()

@webhook_blueprint.route("/home", methods=["POST", "GET"])
def home():
    if request.method == "POST":
        data = request.get_json()  # Retrieve JSON data from the request body
        # Process the data as needed
    
    text = "hey man!"
    return render_template("index.html", text=text)

@webhook_blueprint.route("/subscriptions", methods=["POST", "GET"])
def subscriptions():
    if request.method == "POST":
        request_data = request.get_json()
        return render_template("subscriptions.html", data=request_data)

    elif request.method == "GET":
        args = request.args.to_dict(flat=False)
       
        if 'userName' in args:
            userName = args['userName'][0]
            userName = userName.replace("0", "263", 1)
            
            subscription_plan = session.query(Subscription).filter_by(mobile_number=userName).first()
            if subscription_plan:
                data = subscription_plan.subscription_status
                print("data", data)
                return jsonify(data)
        
    return render_template("subscriptions.html", data="No subs")

@webhook_blueprint.route("/subscription_plan", methods=["POST", "GET"])
def subscription_plan():
    if request.method == "POST":
        data = request.get_json()
        userName = data.get("user_name")
        if userName:
            userName = userName.replace("0", "263", 1)
        try:
            subscription_plan = session.query(Subscription).filter_by(mobile_number=userName).first()
        except Exception as e:
            ...
        if subscription_plan:
            data = {
                "subscription_status": subscription_plan.subscription_status,
                "expiry_date": subscription_plan.trial_end_date,
                "is_active": subscription_plan.is_active,
            }
            return jsonify(data)
        else:
            return jsonify({"error": "You have no active subscription plan"})

    elif request.method == "GET":
        args = request.args.to_dict(flat=False)
        if 'userName' in args:
            userName = args['userName'][0]
            userName = userName.replace("0", "263", 1)
            try:
                subscription_plan = session.query(Subscription).filter_by(mobile_number=userName).first()
            except Exception as e:
                ...
            if subscription_plan:
                data = {
                    "subscription_status": subscription_plan.subscription_status,
                }
                return jsonify(data)

    return jsonify({"error": "Invalid request"})

app/templates/login.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <link
      href="https://fonts.googleapis.com/css?family=Roboto:300,400&display=swap"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static', filename='css/style.css') }}"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static', filename='css/login.css') }}"
    />
    <!-- start -->
    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static', filename='css/bootstrap.min.css') }}"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static', filename='css/owl.carousel.min.css') }}"
    />
    <title>Login | clava</title>
  </head>
  <body style="margin-top: 10%">
    <div class="content">
      <div class="container">
        <div class="row">
          <div class="col-md-6 order-md-2">
            <img
              src="{{ url_for('static', filename='images/undraw_file_sync_ot38.svg') }}"
              alt="Image"
              class="img-fluid"
            />
          </div>
          <div class="col-md-6 contents">
            <div class="row justify-content-center">
              <div class="col-md-8">
                <div class="mb-4">
                  <h3>Sign In to <strong>clavaChat</strong></h3>
                  <p class="mb-4">
                    Manage your business with us and get insights on your
                    data.{{text}}
                  </p>
                </div>
                <form action="/login" method="post" id="login-form">
                  <div class="form-group first">
                    <label for="username">Username | Phone number</label>
                    <input type="text" class="form-control" id="username" />
                  </div>
                  <div class="form-group last mb-4">
                    <label for="password">Password</label>
                    <input type="password" class="form-control" id="password" />
                  </div>
                  <div class="d-flex mb-5 align-items-center">
                    <label class="control control--checkbox mb-0"
                      ><span class="caption">Remember me</span>
                      <input type="checkbox" checked="checked" />
                      <div class="control__indicator"></div>
                    </label>
                    <span class="ml-auto"
                      ><a href="#" class="forgot-pass">Forgot Password</a></span
                    >
                  </div>
                  <input
                    type="submit"
                    value="Log In"
                    class="btn text-white btn-block btn-primary"
                  />
                  <span class="d-block text-left my-4 text-muted">
                    <a href="register">No account?</a></span
                  >
                  <div class="social-login">
                    <a href="#" class="facebook">
                      <span class="icon-facebook mr-3"></span>
                    </a>
                    <a href="#" class="twitter">
                      <span class="icon-twitter mr-3"></span>
                    </a>
                    <a href="#" class="google">
                      <span class="icon-google mr-3"></span>
                    </a>
                  </div>
                </form>
                <div id="flash-message" class="flash-message"></div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <script>
      document
        .getElementById("login-form")
        .addEventListener("submit", function (event) {
          event.preventDefault();
          var username = document.getElementById("username").value;
          var password = document.getElementById("password").value;

          var data = {
            username: username,
            password: password,
          };

          var xhr = new XMLHttpRequest();
          xhr.open("POST", "/login");
          xhr.setRequestHeader("Content-Type", "application/json");
          xhr.onload = function () {
            if (xhr.status === 200) {
              var flashMessage = document.getElementById("flash-message");
              var response = JSON.parse(xhr.responseText);
              flashMessage.textContent = response.message;

              if (response.message === "success") {
                // Login successful
                localStorage.setItem("access_token", response.access_token);
                localStorage.setItem("user_name", username);
                window.location.href = "{{ url_for('webhook.home') }}";
              }
            } else {
              console.error(xhr.responseText);
            }
          };
          xhr.send(JSON.stringify(data));
        });
    </script>
  </body>
</html>

app/templates/register.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <link
      href="https://fonts.googleapis.com/css?family=Roboto:300,400&display=swap"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static', filename='css/style.css') }}"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static', filename='css/login.css') }}"
    />
    <!-- start -->
    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static', filename='css/bootstrap.min.css') }}"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static', filename='css/owl.carousel.min.css') }}"
    />
    <title>Sign Up | clava</title>
  </head>
  <body style="margin-top: 10%">
    <div class="content">
      <div class="container">
        <div class="row">
          <div class="col-md-6 order-md-2">
            <img
              src="{{ url_for('static', filename='images/undraw_file_sync_ot38.svg') }}"
              alt="Image"
              class="img-fluid"
            />
          </div>
          <div class="col-md-6 contents">
            <div class="row justify-content-center">
              <div class="col-md-8">
                <div class="mb-4">
                  <h3>Sign Up <strong>clavaChat</strong></h3>
                </div>
                <form action="/register" method="post" id="login-form">
                  <div class="form-group first">
                    <label for="username">Username | Phone number</label>
                    <input type="text" class="form-control" id="username" />
                  </div>
                  <div class="form-group last mb-4">
                    <label for="password">Password</label>
                    <input type="password" class="form-control" id="password" />
                  </div>
                  <div class="form-group last mb-4">
                    <label for="password">Confirm Password</label>
                    <input type="password" class="form-control" id="password" />
                  </div>
                  
                  <input
                    type="submit"
                    value="register"
                    class="btn text-white btn-block btn-primary"
                  />
                  <span class="d-block text-left my-4 text-muted">
                    <a href="login">Login</a></span
                  >
                </div>
                  <div id="flash-message" class="flash-message"></div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <script>
      document
        .getElementById("login-form")
        .addEventListener("submit", function (event) {
          event.preventDefault();
          var username = document.getElementById("username").value;
          var password = document.getElementById("password").value;

          var data = {
            username: username,
            password: password,
          };

          var xhr = new XMLHttpRequest();
          xhr.open("POST", "/register");
          xhr.setRequestHeader("Content-Type", "application/json");
          xhr.onload = function () {
            if (xhr.status === 200) {
              var flashMessage = document.getElementById("flash-message");
              var response = JSON.parse(xhr.responseText);
              flashMessage.textContent = response.message;

              if (response.message === "success") {
                // Login successful
                localStorage.setItem("access_token", response.access_token);
                localStorage.setItem("user_name", username);
                window.location.href = "{{ url_for('webhook.home') }}";
              }
            } else {
              console.error(xhr.responseText);
            }
          };
          xhr.send(JSON.stringify(data));
        });
    </script>
  </body>
</html>